services:
  - type: web
    name: spc-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
